export default {
  login: "Superdadccs57",
  id: 79618795,
node_id: "MDQ6VXNlcjc5NjE4Nzk1",
avatar_url: "https://avatars.githubusercontent.com/u/79618795?v=4",
gravatar_id: "",
url: "https://api.github.com/users/Superdadccs57",
html_url: "https://github.com/Superdadccs57",
followers_url: "https://api.github.com/users/Superdadccs57/followers",
following_url: "https://api.github.com/users/Superdadccs57/following{/other_user}",
gists_url: "https://api.github.com/users/Superdadccs57/gists{/gist_id}",
starred_url: "https://api.github.com/users/Superdadccs57/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Superdadccs57/subscriptions",
organizations_url: "https://api.github.com/users/Superdadccs57/orgs",
repos_url: "https://api.github.com/users/Superdadccs57/repos",
events_url: "https://api.github.com/users/Superdadccs57/events{/privacy}",
received_events_url: "https://api.github.com/users/Superdadccs57/received_events",
type: "User",
site_admin: false,
name: "Thomas Fentie",
compan: null,
blog: "",
location: null,
email: null,
hireable: null,
bio: "I am a Heavy Duty Mechanic, by trade and now I am looking to fix and solve problems of a different sort!!",
twitter_username: null,
public_repos: 5,
public_gists: 0,
followers: 1,
following: 3,
created_at: "2021-02-25T03:23:37Z",
updated_at: "2022-10-14T20:08:47Z"
};
